// flow-typed signature: 670ab212c840459fb0fb9fda962bf3ce
// flow-typed version: <<STUB>>/eslint-config-defaults_v^9.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-defaults/configurations/airbnb/es5' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/airbnb/es6-react' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/airbnb/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es5-browser' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es5-node' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es5-test' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es5' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6-browser' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6-node' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6-react-test' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6-react' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6-test' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/configurations/walmart/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/best-practices/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/errors/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/es6/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/node/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/strict/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/style/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/eslint' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/google' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/gulp' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/node-runtime' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/eslint/variables/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/filenames/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/filenames/walmart' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/react/airbnb' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/react/off' {
  declare module.exports: any;
}

declare module 'eslint-config-defaults/rules/react/walmart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-defaults/configurations/airbnb/es5.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/airbnb/es5'>;
}
declare module 'eslint-config-defaults/configurations/airbnb/es6-react.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/airbnb/es6-react'>;
}
declare module 'eslint-config-defaults/configurations/airbnb/es6.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/airbnb/es6'>;
}
declare module 'eslint-config-defaults/configurations/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/eslint'>;
}
declare module 'eslint-config-defaults/configurations/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/google'>;
}
declare module 'eslint-config-defaults/configurations/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/gulp'>;
}
declare module 'eslint-config-defaults/configurations/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/node-runtime'>;
}
declare module 'eslint-config-defaults/configurations/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/off'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es5-browser.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es5-browser'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es5-node.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es5-node'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es5-test.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es5-test'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es5.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es5'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6-browser.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6-browser'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6-node.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6-node'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6-react-test.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6-react-test'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6-react.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6-react'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6-test.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6-test'>;
}
declare module 'eslint-config-defaults/configurations/walmart/es6.js' {
  declare module.exports: $Exports<'eslint-config-defaults/configurations/walmart/es6'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/best-practices/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/best-practices/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/errors/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/errors/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/es6/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/es6/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/node/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/node/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/strict/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/strict/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/style/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/style/walmart'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/airbnb'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/eslint.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/eslint'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/google.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/google'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/gulp.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/gulp'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/node-runtime.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/node-runtime'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/off'>;
}
declare module 'eslint-config-defaults/rules/eslint/variables/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/eslint/variables/walmart'>;
}
declare module 'eslint-config-defaults/rules/filenames/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/filenames/off'>;
}
declare module 'eslint-config-defaults/rules/filenames/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/filenames/walmart'>;
}
declare module 'eslint-config-defaults/rules/react/airbnb.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/react/airbnb'>;
}
declare module 'eslint-config-defaults/rules/react/off.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/react/off'>;
}
declare module 'eslint-config-defaults/rules/react/walmart.js' {
  declare module.exports: $Exports<'eslint-config-defaults/rules/react/walmart'>;
}
