# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  # Don't check for updates
  config.vm.box_check_update = false

  # Setup the providers
  config.vm.provider :virtualbox do |vb|
    host = RbConfig::CONFIG['host_os']

    # Give VM 1/4 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    elsif host =~ /mswin|mingw|cygwin/
      # Windows code via https://github.com/rdsubhas/vagrant-faster
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end

    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # Set the box name in VirtualBox to match the working directory.
    devbox_pwd = File.expand_path("..")
    vb.name = File.basename(devbox_pwd)
  end

  # Forward ports
  for c in 2..5
    config.vm.network :forwarded_port, guest: 3306, host: 3306, guest_ip: "172.17.0.#{c}" # mysql
    config.vm.network :forwarded_port, guest: 8000, host: 8000, guest_ip: "172.17.0.#{c}" # nginx
    config.vm.network :forwarded_port, guest: 3000, host: 3000, guest_ip: "172.17.0.#{c}" # redmine

    config.vm.network :forwarded_port, guest: 3306, host: 3306 # mysql
    config.vm.network :forwarded_port, guest: 8000, host: 8000 # nginx
    config.vm.network :forwarded_port, guest: 3000, host: 3000 # redmine
  end
  # config.vm.network "forwarded_port", guest: 3306, host: 3306, guest_ip: "172.17.0.2"      # docker-mysql

  # Network and folder sync
  config.vm.network "private_network", ip: "#{ENV['VAGRANT_IP']}"
  config.vm.hostname = "devbox"

  ## www folder
  config.vm.synced_folder "../../", "/vagrant_project_data", :nfs => { :mount_options => ["dmode=775","fmode=664"] }
  #  config.vm.synced_folder "../", "/vagrant_project_data", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]
  #  config.vm.synced_folder "../", "/vagrant_project_data", type: "rsync", rsync__exclude: "../.git/", rsync__verbose: true

  # Provision
  config.vm.provision "shell" do |s|
    s.args = "#{ENV['VAGRANT_PROJECT_SRC']} #{ENV['VAGRANT_PROJECT_NAME']}"
    s.path = "./provision/bootstrap.sh"
  end
  # config.vm.provision :shell, path: "./provision/bootstrap.sh"
end
